T181172 Internationalize the Timeline
wikimedia/InteractionTimeline pull request #65
Opened 2018-03-06 21:51 UTC by davidbarratt

2018-03-07 18:39 UTC, dayllanmaza requested changes

2018-03-07 18:39 UTC, dayllanmaza commented on i18n/qqq.json
> +		"app-feedback-link": "Provinding a Link for users to leave feedback.",
typo: Providing

2018-03-07 18:39 UTC, dayllanmaza commented on i18n/qqq.json
> +		"privacy-policy": "Link to privacy polciy.",
typo: policy

2018-03-07 18:39 UTC, dayllanmaza commented on i18n/qqq.json
> +		"licensed-under": "Label for the liscense: Licensed under GNU GPLv3",
typo: license

2018-03-07 18:39 UTC, dayllanmaza commented on i18n/qqq.json
> +		"between-interactions": "Suffix to time between. ex: 13 minutes 'between interacitons'",
typo: interactions

2018-03-07 18:39 UTC, dayllanmaza commented on i18n/qqq.json
> +		"error-supressed-diff": "Error message to display when diff cannot be viewed because it is supressed.",
typo: suppressed

2018-03-07 18:39 UTC, dayllanmaza commented on i18n/en.json
> +		"error-supressed-diff": "You cannot view this diff because one or both of the revisions has been suppressed.",
typoe; suppressed

2018-03-07 18:39 UTC, dayllanmaza commented on client/src/components/error-boundary.js
> +		this.state.error = new Error( 'TEST' );
why is this here?

2018-03-07 18:39 UTC, dayllanmaza commented on client/src/components/i18n/message.js
> +const Message = ( { id, placeholders = [] } ) => {
nitpick, Is there a better name for this? `Message` doesn't really reflect that this will print out translations

2018-03-08 19:36 UTC, davidbarratt commented on client/src/components/error-boundary.js
> +		this.state.error = new Error( 'TEST' );
it shouldn't be. :)

2018-03-08 19:36 UTC, davidbarratt commented on client/src/components/i18n/message.js
> +const Message = ( { id, placeholders = [] } ) => {
I borrowed the name from Yahoo's library:
https://github.com/yahoo/react-intl/blob/v2.4.0/src/components/message.js#L16

Also, jQuery.i18n uses the term `Message` a lot:
https://github.com/wikimedia/jquery.i18n
> Messages are key value pairs.

I am open to suggestions though.

2018-03-08 20:01 UTC, dayllanmaza commented on client/src/components/i18n/message.js
> +const Message = ( { id, placeholders = [] } ) => {
That's alright. I can't think of something better tbh

2018-03-08 20:01 UTC, dayllanmaza approved these changes

2018-03-09 15:55 UTC, merged