T197148 Generate wikitext for on-wiki discussions
wikimedia/InteractionTimeline pull request #94
Opened 2018-07-27 17:57 UTC by davidbarratt

and @aezell !

2018-07-27 20:59 UTC, davidbarratt commented
This is ready for review now. :)

2018-08-06 22:02 UTC, davidbarratt commented
This is ready to be tested!

2018-08-08 03:43 UTC, dayllanmaza requested changes
Other than these tiny things, it looks awesome.

2018-08-08 03:43 UTC, dayllanmaza commented on i18n/en.json
> +		"discuss-on-wiki-text": "Between $1 and $2 on $3 [[User:$4]] ([[User talk:$4|talk]] | ([[Special:Contributions/$4|contribs]]) and [[User:$5]] ([[User talk:$5|talk]] | ([[Special:Contributions/$5|co
`Between 2000-01-01 and 2018-08-02 on en.wikipedia.org User:DMaza (talk | (contribs) and ...`
I think there is an unnecessary  `(` before the contribs link

2018-08-08 03:43 UTC, dayllanmaza commented on i18n/en.json
> +		"discus-on-wiki-copy": "Copy",
typos on `discus`

2018-08-08 03:43 UTC, dayllanmaza commented on i18n/qqq.json
> +	"discus-on-wiki-help": "Instructions on what to do with the discuss-on-wiki-text that is presented.",
typos `discus`

2018-08-08 03:43 UTC, dayllanmaza commented on i18n/qqq.json
> +	"discus-on-wiki-copy": "Call to action in discss on wiki modal to copy the wikitext to the clipboard.",
typo `discss`

2018-08-08 03:43 UTC, dayllanmaza commented on client/styles/styles.scss
> +	visibility: visible;
You can probably remove this line; visible is the default value for visibility afaik

2018-08-08 03:43 UTC, dayllanmaza commented on client/src/components/share/share.js
> +				<Button color="light" className={buttonClassName.join( ' ' )} onClick={this.toggle}>
The button overlaps with the footer logo "powered by wikimedia toolforge" when there are only a few interactions or if you scroll all the way down where the footer is visible
Eg: `/?wiki=enwiki&user=75.174.110.184&user=2601%3A1c1%3Ac100%3Aac50%3A781f%3A195d%3A7496%3A2849&startDate=1482710400`

2018-08-08 03:53 UTC, dayllanmaza commented
BTW, I still think we should have as few commits as possible per pull request (ideally 1). Specially if you don't like squashing. 
This will make it easier to track down things (in the rare need of such event). Also easier to roll back since you can keep easily find the previous feature

2018-08-08 20:44 UTC, davidbarratt commented
@dayllanmaza yeah this normally wouldn't have happened, but I had to merge the other issue into this one for testing.

2018-08-09 13:41 UTC, davidbarratt commented
@dayllanmaza I've made all the requested changes, it should be good to review again.

2018-08-09 21:15 UTC, dayllanmaza approved these changes

2018-08-09 21:20 UTC, merged